on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
    secrets:
      TORRE_GITHUB_PACKAGES_TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          TORRE_PACKAGES_TOKEN: ${{ secrets.TORRE_GITHUB_PACKAGES_TOKEN }}

      - run: npm run lint
